Add linters html css
sireclifford/Hello-world pull request #1
Opened 2022-05-24 16:09 UTC by sireclifford

2022-05-24 16:31 UTC, Ismailco requested changes
### Hi @sireclifford,

Good job so far 👍🏼 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding more info to your README file so it would be descriptive and more professional 
- You could consider adding the ```.DS_Store``` file to the ```.gitignore``` file

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-24 16:31 UTC, Ismailco commented on README.md
> +# Hello World
- [ ] This Pull Request should have a descriptive title telling you what changes are inside, you can add a description to this PR with a summary describing introduced changes in more detail

2022-05-24 20:49 UTC, sireclifford commented on README.md
> +# Hello World
@Ismailco thank you for your review. I do not understand how to add description to the pull request. Can you direct me on how to do that please? Thank you

2022-05-24 21:05 UTC, Ismailco commented on README.md
> +# Hello World
@sireclifford, you can click on the ```...``` at the top right of the first comment in this PR and choose ```edit``` 
|||
|--|--|
|![Screenshot_20220524_220401](https://user-images.githubusercontent.com/25227022/170131979-f6ef9e95-b432-43e5-a772-f95709e567f6.png)|![Screenshot_20220524_175736](https://user-images.githubusercontent.com/25227022/170131991-c619dc29-88a2-408e-908a-1c00b86c3145.png)|

2022-05-25 12:27 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @sireclifford,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-25 12:36 UTC, merged